// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(MainDatabase))]
    [Migration("20190706040919_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("ServerId");

                    b.HasKey("ChannelId");

                    b.HasAlternateKey("ServerId", "Name")
                        .HasName("UK_Channel_Server_Name");

                    b.ToTable("Channel");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            Name = "General",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 2,
                            Name = "Boss",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 3,
                            Name = "Random Encounter",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 4,
                            Name = "Origin",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 5,
                            Name = "Ys7",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 6,
                            Name = "Ys8",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 7,
                            Name = "General",
                            ServerId = 3
                        },
                        new
                        {
                            ChannelId = 8,
                            Name = "Secret",
                            ServerId = 3
                        },
                        new
                        {
                            ChannelId = 9,
                            Name = "Sky World",
                            ServerId = 4
                        });
                });

            modelBuilder.Entity("API.Models.ChannelRolePermission", b =>
                {
                    b.Property<int>("ChannelId");

                    b.Property<int>("RoleId");

                    b.Property<string>("PermissionId");

                    b.HasKey("ChannelId", "RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("ChannelRolePermission");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            RoleId = 1,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 2,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 3,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 4,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 1,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 2,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 3,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 4,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 1,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 2,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 3,
                            PermissionId = "no_chat"
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 4,
                            PermissionId = "no_chat"
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 5,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 6,
                            PermissionId = "no_view"
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 7,
                            PermissionId = "no_view"
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 5,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 6,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 7,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 5,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 6,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 7,
                            PermissionId = "no_view"
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 8,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 9,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 10,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 8,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 9,
                            PermissionId = "full"
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 10,
                            PermissionId = "no_chat"
                        },
                        new
                        {
                            ChannelId = 9,
                            RoleId = 11,
                            PermissionId = "full"
                        });
                });

            modelBuilder.Entity("API.Models.InstantInvite", b =>
                {
                    b.Property<string>("Link")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("NerverExpire");

                    b.Property<int>("ServerId");

                    b.HasKey("Link");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("InstantInvite");

                    b.HasData(
                        new
                        {
                            Link = "1",
                            NerverExpire = true,
                            ServerId = 1
                        },
                        new
                        {
                            Link = "2",
                            NerverExpire = true,
                            ServerId = 2
                        },
                        new
                        {
                            Link = "3",
                            NerverExpire = true,
                            ServerId = 3
                        },
                        new
                        {
                            Link = "4",
                            NerverExpire = true,
                            ServerId = 4
                        });
                });

            modelBuilder.Entity("API.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Time");

                    b.Property<int>("UserId");

                    b.HasKey("MessageId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ChannelId = 1,
                            Content = "This is the first message in final fantasy",
                            Time = new DateTime(2019, 1, 1, 0, 0, 0, 1, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            ChannelId = 1,
                            Content = "And this is the second message in final fantasy",
                            Time = new DateTime(2019, 1, 2, 0, 0, 1, 245, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            ChannelId = 1,
                            Content = "AAAAAAAAAA",
                            Time = new DateTime(2019, 1, 2, 0, 0, 2, 368, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 4,
                            ChannelId = 2,
                            Content = "Another channel in final fantasy",
                            Time = new DateTime(2019, 1, 2, 0, 0, 1, 123, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 5,
                            ChannelId = 2,
                            Content = "BBBBBBBBBBBBBB",
                            Time = new DateTime(2019, 1, 2, 0, 0, 2, 899, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 6,
                            ChannelId = 2,
                            Content = "Hi there",
                            Time = new DateTime(2019, 1, 2, 0, 0, 3, 543, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("API.Models.Permission", b =>
                {
                    b.Property<string>("PermissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("PermissionId");

                    b.ToTable("Permission");

                    b.HasData(
                        new
                        {
                            PermissionId = "full",
                            Description = "Will allow users to do anything",
                            Name = "full"
                        },
                        new
                        {
                            PermissionId = "no_react",
                            Description = "Won't allow users to give reactions",
                            Name = "no react"
                        },
                        new
                        {
                            PermissionId = "no_chat",
                            Description = "Won't allow users to chat",
                            Name = "no chat"
                        },
                        new
                        {
                            PermissionId = "no_view",
                            Description = "Won't allow users to see anything",
                            Name = "no view"
                        });
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("ServerId");

                    b.HasKey("RoleId");

                    b.HasIndex("ServerId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Knight",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Thief",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "White Wizard",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Black Wizard",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Adol",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 6,
                            Name = "Dogi",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 7,
                            Name = "Aisha",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 8,
                            Name = "Admin",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 9,
                            Name = "Artist",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 10,
                            Name = "Folk",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 11,
                            Name = "Musician",
                            ServerId = 4
                        });
                });

            modelBuilder.Entity("API.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("ServerId");

                    b.HasIndex("AdminId");

                    b.ToTable("Server");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            AdminId = 1,
                            Image = "server_1.png",
                            Name = "Final Fantasy"
                        },
                        new
                        {
                            ServerId = 2,
                            AdminId = 1,
                            Image = "server_2.png",
                            Name = "Ys"
                        },
                        new
                        {
                            ServerId = 3,
                            AdminId = 2,
                            Image = "server_3.png",
                            Name = "Maiden"
                        },
                        new
                        {
                            ServerId = 4,
                            AdminId = 2,
                            Name = "TSFH"
                        });
                });

            modelBuilder.Entity("API.Models.ServerUser", b =>
                {
                    b.Property<int>("ServerId");

                    b.Property<int>("UserId");

                    b.HasKey("ServerId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ServerUser");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            UserId = 1
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 1
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 2
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 2
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 3
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 2
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 3
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 4
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 1
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 4
                        },
                        new
                        {
                            ServerId = 4,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("FirstName");

                    b.Property<int?>("Gender");

                    b.Property<string>("Image");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.HasAlternateKey("Email")
                        .HasName("UK_User_Email");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "daophilac@gmail.com",
                            FirstName = "Đào Phi",
                            Gender = 0,
                            Image = "user_1.png",
                            LastName = "Lạc",
                            Password = "123",
                            Username = "peanut"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "daophilac1@gmail.com",
                            FirstName = "Đào Phi",
                            Gender = 0,
                            Image = "user_2.png",
                            LastName = "Lạc",
                            Password = "123",
                            Username = "peanut"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "lucknight@gmail.com",
                            FirstName = "luck",
                            Gender = 0,
                            Image = "user_3.png",
                            LastName = "night",
                            Password = "123",
                            Username = "lucknight"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "eddie@gmail.com",
                            FirstName = "ed",
                            Gender = 0,
                            Image = "user_4.png",
                            LastName = "die",
                            Password = "123",
                            Username = "eddie"
                        });
                });

            modelBuilder.Entity("API.Models.Channel", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.ChannelRolePermission", b =>
                {
                    b.HasOne("API.Models.Channel", "Channel")
                        .WithMany("ChannelRolePermissions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Permission", "Permission")
                        .WithMany("ChannelRolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("ChannelRolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API.Models.InstantInvite", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithOne("InstantInvite")
                        .HasForeignKey("API.Models.InstantInvite", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.Message", b =>
                {
                    b.HasOne("API.Models.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("Roles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.Server", b =>
                {
                    b.HasOne("API.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.ServerUser", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("ServerUsers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.User", "User")
                        .WithMany("ServerUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
