// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(MainDatabase))]
    partial class MainDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ServerId");

                    b.HasKey("ChannelId");

                    b.HasAlternateKey("ServerId", "ChannelName")
                        .HasName("UK_Channel_Server_Name");

                    b.ToTable("Channel");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            ChannelName = "General",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 2,
                            ChannelName = "Boss",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 3,
                            ChannelName = "Random Encounter",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 4,
                            ChannelName = "Origin",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 5,
                            ChannelName = "Ys7",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 6,
                            ChannelName = "Ys8",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 7,
                            ChannelName = "General",
                            ServerId = 3
                        },
                        new
                        {
                            ChannelId = 8,
                            ChannelName = "Secret",
                            ServerId = 3
                        },
                        new
                        {
                            ChannelId = 9,
                            ChannelName = "Sky World",
                            ServerId = 4
                        });
                });

            modelBuilder.Entity("API.Models.ChannelLevelPermission", b =>
                {
                    b.Property<int>("ChannelId");

                    b.Property<int>("RoleId");

                    b.Property<int>("ChannelPermissionId");

                    b.Property<bool>("IsActive");

                    b.HasKey("ChannelId", "RoleId", "ChannelPermissionId");

                    b.HasIndex("ChannelPermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("ChannelLevelPermission");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            RoleId = 1,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 2,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 9,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 10,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 11,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 12,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 1,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 2,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 9,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 10,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 11,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 12,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 1,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 2,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 9,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 10,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 11,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 12,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 3,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 4,
                            ChannelPermissionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 13,
                            ChannelPermissionId = 2,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 14,
                            ChannelPermissionId = 2,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 15,
                            ChannelPermissionId = 2,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 3,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 4,
                            ChannelPermissionId = 2,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 13,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 14,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 15,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 3,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 4,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 13,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 14,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 15,
                            ChannelPermissionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 5,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 6,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 16,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 17,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 18,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 5,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 6,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 16,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 17,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 18,
                            ChannelPermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            ChannelId = 9,
                            RoleId = 7,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 9,
                            RoleId = 8,
                            ChannelPermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            ChannelId = 9,
                            RoleId = 19,
                            ChannelPermissionId = 1,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("API.Models.ChannelPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(1024)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("PermissionId");

                    b.ToTable("ChannelPermission");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "All"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionName = "All except send message"
                        },
                        new
                        {
                            PermissionId = 3,
                            PermissionName = "View message"
                        },
                        new
                        {
                            PermissionId = 4,
                            PermissionName = "Send message"
                        },
                        new
                        {
                            PermissionId = 5,
                            PermissionName = "Send image"
                        },
                        new
                        {
                            PermissionId = 6,
                            PermissionName = "React"
                        });
                });

            modelBuilder.Entity("API.Models.InstantInvite", b =>
                {
                    b.Property<string>("Link")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<bool>("NerverExpired");

                    b.Property<int>("ServerId");

                    b.Property<bool>("StillValid");

                    b.HasKey("Link");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("InstantInvite");

                    b.HasData(
                        new
                        {
                            Link = "1",
                            NerverExpired = true,
                            ServerId = 1,
                            StillValid = true
                        },
                        new
                        {
                            Link = "2",
                            NerverExpired = true,
                            ServerId = 2,
                            StillValid = true
                        },
                        new
                        {
                            Link = "3",
                            NerverExpired = true,
                            ServerId = 3,
                            StillValid = true
                        },
                        new
                        {
                            Link = "4",
                            NerverExpired = true,
                            ServerId = 4,
                            StillValid = true
                        });
                });

            modelBuilder.Entity("API.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Time");

                    b.Property<int>("UserId");

                    b.HasKey("MessageId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ChannelId = 1,
                            Content = "This is the first message in final fantasy",
                            Time = new DateTime(2019, 1, 1, 0, 0, 0, 1, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            ChannelId = 1,
                            Content = "And this is the second message in final fantasy",
                            Time = new DateTime(2019, 1, 2, 0, 0, 1, 245, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            ChannelId = 1,
                            Content = "AAAAAAAAAA",
                            Time = new DateTime(2019, 1, 2, 0, 0, 2, 368, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 4,
                            ChannelId = 2,
                            Content = "Another channel in final fantasy",
                            Time = new DateTime(2019, 1, 2, 0, 0, 1, 123, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 5,
                            ChannelId = 2,
                            Content = "BBBBBBBBBBBBBB",
                            Time = new DateTime(2019, 1, 2, 0, 0, 2, 899, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 6,
                            ChannelId = 2,
                            Content = "Hi there",
                            Time = new DateTime(2019, 1, 2, 0, 0, 3, 543, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ServerId");

                    b.HasKey("RoleId");

                    b.HasIndex("ServerId");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Member",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Admin",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Member",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Admin",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 6,
                            RoleName = "Member",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 7,
                            RoleName = "Admin",
                            ServerId = 4
                        },
                        new
                        {
                            RoleId = 8,
                            RoleName = "Member",
                            ServerId = 4
                        },
                        new
                        {
                            RoleId = 9,
                            RoleName = "Knight",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 10,
                            RoleName = "Thief",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 11,
                            RoleName = "White Wizard",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 12,
                            RoleName = "Black Wizard",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 13,
                            RoleName = "Adol",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 14,
                            RoleName = "Dogi",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 15,
                            RoleName = "Aisha",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 16,
                            RoleName = "New Admin",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 17,
                            RoleName = "Artist",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 18,
                            RoleName = "Folk",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 19,
                            RoleName = "Musician",
                            ServerId = 4
                        });
                });

            modelBuilder.Entity("API.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int?>("DefaultRoleId");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(254);

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ServerId");

                    b.HasIndex("AdminId");

                    b.ToTable("Server");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            AdminId = 1,
                            DefaultRoleId = 2,
                            ImageUrl = "server_1.png",
                            ServerName = "Final Fantasy"
                        },
                        new
                        {
                            ServerId = 2,
                            AdminId = 1,
                            DefaultRoleId = 4,
                            ImageUrl = "server_2.png",
                            ServerName = "Ys"
                        },
                        new
                        {
                            ServerId = 3,
                            AdminId = 2,
                            DefaultRoleId = 6,
                            ImageUrl = "server_3.png",
                            ServerName = "Maiden"
                        },
                        new
                        {
                            ServerId = 4,
                            AdminId = 2,
                            DefaultRoleId = 8,
                            ServerName = "TSFH"
                        });
                });

            modelBuilder.Entity("API.Models.ServerLevelPermission", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("PermissionId");

                    b.Property<bool>("IsActive");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ServerLevelPermission");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 9,
                            PermissionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 10,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 11,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 12,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 13,
                            PermissionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 14,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 15,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 16,
                            PermissionId = 2,
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 17,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 18,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 7,
                            PermissionId = 1,
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 8,
                            PermissionId = 1,
                            IsActive = false
                        },
                        new
                        {
                            RoleId = 19,
                            PermissionId = 2,
                            IsActive = true
                        });
                });

            modelBuilder.Entity("API.Models.ServerPermission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(1024)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("PermissionId");

                    b.ToTable("ServerPermission");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            PermissionName = "All"
                        },
                        new
                        {
                            PermissionId = 2,
                            PermissionName = "All except kick"
                        },
                        new
                        {
                            PermissionId = 3,
                            PermissionName = "Kick"
                        },
                        new
                        {
                            PermissionId = 4,
                            PermissionName = "Modify channel"
                        },
                        new
                        {
                            PermissionId = 5,
                            PermissionName = "Modify role"
                        });
                });

            modelBuilder.Entity("API.Models.ServerUser", b =>
                {
                    b.Property<int>("ServerId");

                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("ServerId", "UserId");

                    b.HasAlternateKey("ServerId", "UserId", "RoleId")
                        .HasName("UK_ServerUser_ServerId_UserId_RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("ServerUser");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 2,
                            RoleId = 5
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 2,
                            RoleId = 9
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 3,
                            RoleId = 9
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 2,
                            RoleId = 13
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 3,
                            RoleId = 13
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 4,
                            RoleId = 13
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 1,
                            RoleId = 16
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 4,
                            RoleId = 16
                        },
                        new
                        {
                            ServerId = 4,
                            UserId = 2,
                            RoleId = 7
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(254)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30);

                    b.Property<int>("Gender");

                    b.Property<string>("ImageName")
                        .HasMaxLength(254);

                    b.Property<string>("LastName")
                        .HasMaxLength(30);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Phone")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("UserId");

                    b.HasAlternateKey("Email")
                        .HasName("UK_User_Email");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "daophilac@gmail.com",
                            FirstName = "Đào Phi",
                            Gender = 0,
                            ImageName = "user_1.png",
                            LastName = "Lạc",
                            Password = "123",
                            Username = "peanut"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "daophilac1@gmail.com",
                            FirstName = "Đào Phi",
                            Gender = 0,
                            ImageName = "user_2.png",
                            LastName = "Lạc",
                            Password = "123",
                            Username = "peanut"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "lucknight@gmail.com",
                            FirstName = "luck",
                            Gender = 0,
                            ImageName = "user_3.png",
                            LastName = "night",
                            Password = "123",
                            Username = "lucknight"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "eddie@gmail.com",
                            FirstName = "ed",
                            Gender = 0,
                            ImageName = "user_4.png",
                            LastName = "die",
                            Password = "123",
                            Username = "eddie"
                        });
                });

            modelBuilder.Entity("API.Models.Channel", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.ChannelLevelPermission", b =>
                {
                    b.HasOne("API.Models.Channel", "Channel")
                        .WithMany("ChannelLevelPermissions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.ChannelPermission", "ChannelPermission")
                        .WithMany("ChannelLevelPermissions")
                        .HasForeignKey("ChannelPermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("ChannelLevelPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API.Models.InstantInvite", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithOne("InstantInvite")
                        .HasForeignKey("API.Models.InstantInvite", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.Message", b =>
                {
                    b.HasOne("API.Models.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("Roles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.Server", b =>
                {
                    b.HasOne("API.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.ServerLevelPermission", b =>
                {
                    b.HasOne("API.Models.ServerPermission", "ServerPermission")
                        .WithMany("ServerLevelPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("ServerLevelPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.ServerUser", b =>
                {
                    b.HasOne("API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("ServerUsers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.User", "User")
                        .WithMany("ServerUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
