// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(MainDatabase))]
    partial class MainDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ServerId");

                    b.HasKey("ChannelId");

                    b.HasIndex("ServerId", "ChannelName")
                        .IsUnique();

                    b.ToTable("Channel");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            ChannelName = "General",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 2,
                            ChannelName = "Boss",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 3,
                            ChannelName = "Random Encounter",
                            ServerId = 1
                        },
                        new
                        {
                            ChannelId = 4,
                            ChannelName = "Origin",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 5,
                            ChannelName = "Ys7",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 6,
                            ChannelName = "Ys8",
                            ServerId = 2
                        },
                        new
                        {
                            ChannelId = 7,
                            ChannelName = "General",
                            ServerId = 3
                        },
                        new
                        {
                            ChannelId = 8,
                            ChannelName = "Secret",
                            ServerId = 3
                        },
                        new
                        {
                            ChannelId = 9,
                            ChannelName = "Sky World",
                            ServerId = 4
                        });
                });

            modelBuilder.Entity("API.Models.ChannelPermission", b =>
                {
                    b.Property<int>("ChannelId");

                    b.Property<int>("RoleId");

                    b.Property<bool>("React");

                    b.Property<bool>("SendImage");

                    b.Property<bool>("SendMessage");

                    b.Property<bool>("ViewMessage");

                    b.HasKey("ChannelId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("ChannelPermission");

                    b.HasData(
                        new
                        {
                            ChannelId = 1,
                            RoleId = 1,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 2,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 9,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 10,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 11,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 1,
                            RoleId = 12,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 1,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 2,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 9,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 10,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 11,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 2,
                            RoleId = 12,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 1,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 2,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 9,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 10,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 11,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 3,
                            RoleId = 12,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 3,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 4,
                            React = true,
                            SendImage = true,
                            SendMessage = false,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 13,
                            React = true,
                            SendImage = true,
                            SendMessage = false,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 14,
                            React = true,
                            SendImage = true,
                            SendMessage = false,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 4,
                            RoleId = 15,
                            React = true,
                            SendImage = true,
                            SendMessage = false,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 3,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 4,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 13,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 14,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 5,
                            RoleId = 15,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 3,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 4,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 13,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 14,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 6,
                            RoleId = 15,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 5,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 6,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 16,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 17,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 7,
                            RoleId = 18,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 5,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 6,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 16,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 17,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 8,
                            RoleId = 18,
                            React = false,
                            SendImage = false,
                            SendMessage = false,
                            ViewMessage = false
                        },
                        new
                        {
                            ChannelId = 9,
                            RoleId = 7,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 9,
                            RoleId = 8,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        },
                        new
                        {
                            ChannelId = 9,
                            RoleId = 19,
                            React = true,
                            SendImage = true,
                            SendMessage = true,
                            ViewMessage = true
                        });
                });

            modelBuilder.Entity("API.Models.InstantInvite", b =>
                {
                    b.Property<string>("Link")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("NerverExpired");

                    b.Property<int>("ServerId");

                    b.Property<bool>("StillValid");

                    b.HasKey("Link");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("InstantInvite");

                    b.HasData(
                        new
                        {
                            Link = "e4912f82-d290-40e6-a23d-08d0ce1b50ab",
                            NerverExpired = true,
                            ServerId = 1,
                            StillValid = true
                        },
                        new
                        {
                            Link = "648d7e41-75f9-48b8-8bb2-ccf1ffa74245",
                            NerverExpired = true,
                            ServerId = 2,
                            StillValid = true
                        },
                        new
                        {
                            Link = "15f0529f-53b9-46b9-8bb6-8d8d863eb167",
                            NerverExpired = true,
                            ServerId = 3,
                            StillValid = true
                        },
                        new
                        {
                            Link = "5766df3a-3e31-4c1c-b50c-bc887efd4626",
                            NerverExpired = true,
                            ServerId = 4,
                            StillValid = true
                        });
                });

            modelBuilder.Entity("API.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChannelId");

                    b.Property<string>("Content");

                    b.Property<DateTime>("Time");

                    b.Property<int>("UserId");

                    b.HasKey("MessageId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("UserId");

                    b.ToTable("Message");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ChannelId = 1,
                            Content = "This is the first message in final fantasy",
                            Time = new DateTime(2019, 1, 1, 0, 0, 0, 1, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 2,
                            ChannelId = 1,
                            Content = "And this is the second message in final fantasy",
                            Time = new DateTime(2019, 1, 2, 0, 0, 1, 245, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            MessageId = 3,
                            ChannelId = 1,
                            Content = "AAAAAAAAAA",
                            Time = new DateTime(2019, 1, 2, 0, 0, 2, 368, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            MessageId = 4,
                            ChannelId = 2,
                            Content = "Another channel in final fantasy",
                            Time = new DateTime(2019, 1, 2, 0, 0, 1, 123, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 5,
                            ChannelId = 2,
                            Content = "BBBBBBBBBBBBBB",
                            Time = new DateTime(2019, 1, 2, 0, 0, 2, 899, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            MessageId = 6,
                            ChannelId = 2,
                            Content = "Hi there",
                            Time = new DateTime(2019, 1, 2, 0, 0, 3, 543, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ChangeUserRole");

                    b.Property<bool>("Kick");

                    b.Property<bool>("MainRole");

                    b.Property<bool>("ModifyChannel");

                    b.Property<bool>("ModifyRole");

                    b.Property<int>("RoleLevel");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("ServerId");

                    b.HasKey("RoleId");

                    b.HasIndex("ServerId", "RoleLevel")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            ChangeUserRole = true,
                            Kick = true,
                            MainRole = true,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 1000,
                            RoleName = "Admin",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = true,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 0,
                            RoleName = "Member",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            ChangeUserRole = true,
                            Kick = true,
                            MainRole = true,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 1000,
                            RoleName = "Admin",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 4,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = true,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 0,
                            RoleName = "Member",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 5,
                            ChangeUserRole = true,
                            Kick = true,
                            MainRole = true,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 1000,
                            RoleName = "Admin",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 6,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = true,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 0,
                            RoleName = "Member",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 7,
                            ChangeUserRole = true,
                            Kick = true,
                            MainRole = true,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 1000,
                            RoleName = "Admin",
                            ServerId = 4
                        },
                        new
                        {
                            RoleId = 8,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = true,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 0,
                            RoleName = "Member",
                            ServerId = 4
                        },
                        new
                        {
                            RoleId = 9,
                            ChangeUserRole = true,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 900,
                            RoleName = "Knight",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 10,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 800,
                            RoleName = "Thief",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 11,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 700,
                            RoleName = "White Wizard",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 12,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 699,
                            RoleName = "Black Wizard",
                            ServerId = 1
                        },
                        new
                        {
                            RoleId = 13,
                            ChangeUserRole = true,
                            Kick = true,
                            MainRole = false,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 900,
                            RoleName = "Adol",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 14,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 800,
                            RoleName = "Dogi",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 15,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 700,
                            RoleName = "Aisha",
                            ServerId = 2
                        },
                        new
                        {
                            RoleId = 16,
                            ChangeUserRole = true,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 900,
                            RoleName = "New Admin",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 17,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 800,
                            RoleName = "Artist",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 18,
                            ChangeUserRole = false,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = false,
                            ModifyRole = false,
                            RoleLevel = 700,
                            RoleName = "Folk",
                            ServerId = 3
                        },
                        new
                        {
                            RoleId = 19,
                            ChangeUserRole = true,
                            Kick = false,
                            MainRole = false,
                            ModifyChannel = true,
                            ModifyRole = true,
                            RoleLevel = 500,
                            RoleName = "Musician",
                            ServerId = 4
                        });
                });

            modelBuilder.Entity("API.Models.Server", b =>
                {
                    b.Property<int>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId");

                    b.Property<int?>("DefaultRoleId");

                    b.Property<string>("ImageName")
                        .HasMaxLength(254);

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ServerId");

                    b.HasIndex("AdminId");

                    b.ToTable("Server");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            AdminId = 1,
                            DefaultRoleId = 2,
                            ImageName = "server_1.png",
                            ServerName = "Final Fantasy"
                        },
                        new
                        {
                            ServerId = 2,
                            AdminId = 1,
                            DefaultRoleId = 4,
                            ImageName = "server_2.png",
                            ServerName = "Ys"
                        },
                        new
                        {
                            ServerId = 3,
                            AdminId = 2,
                            DefaultRoleId = 6,
                            ImageName = "server_3.png",
                            ServerName = "Maiden"
                        },
                        new
                        {
                            ServerId = 4,
                            AdminId = 2,
                            DefaultRoleId = 8,
                            ServerName = "TSFH"
                        });
                });

            modelBuilder.Entity("API.Models.ServerUser", b =>
                {
                    b.Property<int>("ServerId");

                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("ServerId", "UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("ServerId", "UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("ServerUser");

                    b.HasData(
                        new
                        {
                            ServerId = 1,
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 2,
                            RoleId = 9
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 3,
                            RoleId = 9
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 5,
                            RoleId = 10
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 6,
                            RoleId = 11
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 7,
                            RoleId = 12
                        },
                        new
                        {
                            ServerId = 1,
                            UserId = 8,
                            RoleId = 11
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 1,
                            RoleId = 3
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 2,
                            RoleId = 13
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 3,
                            RoleId = 13
                        },
                        new
                        {
                            ServerId = 2,
                            UserId = 4,
                            RoleId = 15
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 2,
                            RoleId = 5
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 1,
                            RoleId = 16
                        },
                        new
                        {
                            ServerId = 3,
                            UserId = 4,
                            RoleId = 16
                        },
                        new
                        {
                            ServerId = 4,
                            UserId = 2,
                            RoleId = 7
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(254)");

                    b.Property<string>("ImageName")
                        .HasMaxLength(254);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Phone")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "daophilac@gmail.com",
                            ImageName = "user_1.png",
                            Password = "123",
                            UserName = "peanut"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "adol@gmail.com",
                            ImageName = "user_2.png",
                            Password = "123",
                            UserName = "adol"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "lucknight@gmail.com",
                            ImageName = "user_3.png",
                            Password = "123",
                            UserName = "lucknight"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "eddie@gmail.com",
                            ImageName = "user_4.png",
                            Password = "123",
                            UserName = "eddie"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "locke@gmail.com",
                            ImageName = "user_5.png",
                            Password = "123",
                            UserName = "lock"
                        },
                        new
                        {
                            UserId = 6,
                            Email = "terra@gmail.com",
                            ImageName = "user_6.png",
                            Password = "123",
                            UserName = "terra"
                        },
                        new
                        {
                            UserId = 7,
                            Email = "celes@gmail.com",
                            ImageName = "user_7.png",
                            Password = "123",
                            UserName = "celes"
                        },
                        new
                        {
                            UserId = 8,
                            Email = "aeris@gmail.com",
                            ImageName = "user_8.jpg",
                            Password = "123",
                            UserName = "aeris"
                        },
                        new
                        {
                            UserId = 9,
                            Email = "test@gmail.com",
                            Password = "123",
                            UserName = "test"
                        });
                });

            modelBuilder.Entity("API.Models.Channel", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("Channels")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.ChannelPermission", b =>
                {
                    b.HasOne("API.Models.Channel", "Channel")
                        .WithMany("ChannelLevelPermissions")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("ChannelPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API.Models.InstantInvite", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithOne("InstantInvite")
                        .HasForeignKey("API.Models.InstantInvite", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.Message", b =>
                {
                    b.HasOne("API.Models.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("Roles")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.Server", b =>
                {
                    b.HasOne("API.Models.User", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("API.Models.ServerUser", b =>
                {
                    b.HasOne("API.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("API.Models.Server", "Server")
                        .WithMany("ServerUsers")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API.Models.User", "User")
                        .WithMany("ServerUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
